---
- name: Set timezone
  timezone:
    name: "{{ timedatectl_timezone }}"

- name: Change timedatectl condition
  lineinfile:
    dest: /usr/lib/systemd/system/systemd-timesyncd.service
    regexp: "^ConditionVirtualization=!container"
    line: "#ConditionVirtualization=!container"
    state: present
  notify:
    - daemon reload

- name: Set ntp config
  lineinfile:
    dest: /etc/systemd/timesyncd.conf
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
    state: present
  loop:
    - {regexp: '^#NTP=$', line: 'NTP={{ntp_servers}}'}
    - {regexp: '^#FallbackNTP', line: 'FallbackNTP={{fallback_NTP}}'}
  notify:
    - run Timedatectl
    - start Timedatectl

- name: Enable timedatectl ntp service
  command: timedatectl set-ntp true


- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: Install minimum soft
  ansible.builtin.package:
    name:
      - vim
      - mc
      - htop
    state: present  

- name: En a locale exists
  community.general.locale_gen:
    name: en_US.UTF-8
    state: present

- name: Ru a locale exists
  community.general.locale_gen:
    name: ru_RU.UTF-8
    state: present

- name: Update locale
  shell: update-locale LANG=ru_RU.UTF-8

- name: Keyboard config
  copy:
    src: keyboard
    dest: /etc/default/keyboard
    owner: root
    group: root
    mode: 0644
    backup: yes